name: calculadora_taxa
description: App para calcular as taxas com base no valor base

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0
  equatable: ^2.0.5
  result_dart: ^1.0.5
  go_router: ^6.5.5
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2
  mocktail: ^0.3.0


flutter:
  uses-material-design: true
